apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: helloworld-angular8
#   apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
  name: helloworld-angular8
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"

  build:
    env:
    - name: BP_NODE_RUN_SCRIPTS
      value: "build"
    - name: BP_WEB_SERVER
      value: "nginx"
    - name: BP_WEB_SERVER_ROOT
      value: "dist"
    - name: BP_WEB_SERVER_ENABLE_PUSH_STATE
      value: "true"
    - name: BP_NODE_VERSION
      value: "16.20.1"
  source:
    git:
      ref:
        branch: master
      url: https://github.com/egedsoft/helloworld-angular8
